apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Register deployed artifact'
description: 'Creates an artifact version association with the environment.'

inputs:
  artifact-id:
    description: 'The unique identifier of an artifact.'
    required: true
  target-environment:
    description: 'The environment where the deployment occurred.'
  labels:
    description: 'List of comma-separated labels.'

runs:
  using: composite
  steps:
    - id: registerDeployedArtifact
      name: Register Deployed Artifact
      uses: docker://esolang/jq:latest
      run: |
        # Set the fold width to match the table column width
        FOLD_WIDTH=48
        
        # Helper function to fold and print a parameter name and value 
        fold_and_print() {
          local pName="$1"
          local pValue="$2"
          folded=$(echo "$pValue" | fold -s -w $FOLD_WIDTH)
          first=1
          echo "$folded" | while IFS= read -r line; do
          if [ "$first" -eq 1 ]; then
            printf "| \033[1m%-20s\033[0m | %-50s |\n" "$pName" "$line"
            first=0
          else
            printf "| \033[1m%-20s\033[0m | %-50s |\n" "" "$line"
          fi
        done
        }
        
        # Function to print inputs in a formatted table
        print_inputs() {
          echo "+----------------------+----------------------------------------------------+"
          printf "| \033[1m%-20s\033[0m | \033[1m%-50s\033[0m |\n" "Parameter" "Value"
          echo "+----------------------+----------------------------------------------------+"
          printf "| \033[1m%-20s\033[0m | %-50s |\n" "artifact-id" "$INPUT_ARTIFACT_ID"
          printf "| \033[1m%-20s\033[0m | %-50s |\n" "target-environment" "$INPUT_TARGET_ENV"
          fold_and_print "labels" "$INPUT_LABELS"
          echo "+----------------------+----------------------------------------------------+"        
        }
        
        # Create the payload JSON file
        echo '{ "runId": "'"$CLOUDBEES_RUN_ID"'", "runAttempt": "'"$CLOUDBEES_RUN_ATTEMPT"'",' > /tmp/payload.json 
        echo '"artifactId": "'"$INPUT_ARTIFACT_ID"'" ' >> /tmp/payload.json

        # Add target-environment if provided
        if [ -n "$INPUT_TARGET_ENV" ]; 
        then
          echo ', "environment": "'"$INPUT_TARGET_ENV"'"' >> /tmp/payload.json
        fi
        
        if [ -n "$INPUT_LABELS" ]; 
        then
         # Convert labels to JSON array format
         formatted_labels=$(echo "$INPUT_LABELS" | sed -e 's/[][]//g' | awk -v RS=, -v ORS=, '{ gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "");  gsub(/\\"/, "\\\\\""); gsub(/"/, "\\\""); printf "\"%s\",", $0 }' | sed 's/,$//' | sed 's/^/[/; s/$/]/')
         echo ', "labels": '"$formatted_labels">> /tmp/payload.json
        fi
        echo ' }' >> /tmp/payload.json
        
        # Display the generated payload
        echo "Request payload:"
        print_inputs

        echo "Request raw payload:"
        cat /tmp/payload.json
        
        # Make CloudBees Unify API call to create artifact_info record
        response=$(curl --retry 5 --retry-delay 10 --retry-all-errors --silent --show-error --fail-with-body \
          -X 'POST' "$URL/v3/deployments" \
          -H "Authorization: Bearer $JWT" \
          -H 'Content-Type: application/json' \
          --data-binary '@/tmp/payload.json') || command_failed=1
       
        # Check if the API call failed
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo "CloudBees Unify API call failed with error: $response"
          exit 1
        fi
        
        # If successful, show the response nicely
        echo ""
        echo "CloudBees Unify API success response:"
        echo "$response" | /usr/bin/jq || echo "$response"
      env:
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
        INPUT_ARTIFACT_ID: ${{ inputs.artifact-id }}
        INPUT_TARGET_ENV: ${{ inputs.target-environment }}
        INPUT_LABELS: ${{ inputs.labels }}
        CLOUDBEES_RUN_ID: ${{ cloudbees.run_id }}
        CLOUDBEES_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}

