
= CloudBees action: Register an artifact deployed to an environment

Use this action to report artifact-related data to an environment from a CloudBees platform workflow run, for artifact traceability purposes.

== Prerequisites

Before using this action, you must first register the artifact you plan to deploy to an environment.
This registration saves the artifact information to the platform.

Do one of the following to save your artifact information to the platform:

* Use the link:https://github.com/cloudbees-io/register-build-artifact[Register a build artifact] action in your workflow in a step prior to using this action.

* Add a publishing step to your workflow prior to using this action.
For example, use one of the following actions:
** link:https://github.com/cloudbees-io/ecr-promote-image[]
** link:https://github.com/cloudbees-io/s3-upload-object[]
** link:https://github.com/cloudbees-io/crane[]
** link:https://github.com/cloudbees-io/helm-push[]
** link:https://github.com/cloudbees-io/jfrog-artifactory-promote-image[]
** link:https://github.com/cloudbees-io/jfrog-artifactory-upload-file[]
** link:https://github.com/cloudbees-io/kaniko[]

* Manually link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/artifacts#create-artifact-version[create an artifact version] in the UI.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `artifact_id`
| String
| Yes
| The unique identifier of an artifact.

| `target-environment`
| String
| No
| The environment where the deployment is located.  
The `target-environment` value overrides the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/dsl-syntax/jobs-job-id-environment[`jobs.<job_id>.environment`] value.

| `labels`
| String
| No
| A comma-separated list of artifact labels.


|===

== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
 jobs:
    register_artifact_version_to_test_env:
      environment: test_env
      steps:
        - name: Register deployed artifact
          uses: cloudbees-io/register-deployed-artifact@v1
          with:
            artifact_id: "00000000-0000-0000-0000-000000000001"
            target-environment: "test_env"
----

=== Using optional inputs

The following example specifies labels:

[source,yaml]
----
 jobs:
    register_artifact_version_to_qa_env:
      environment: qa_env
      steps:
        - name: Register deployed artifact with labels and digest
          uses: cloudbees-io/register-deployed-artifact@v1
          with:
            artifact_id: "00000000-0000-0000-0000-000000000001"
            labels: "label1,label2"
----

=== Full workflow example with Kaniko

This example publishes an image with link:https://github.com/cloudbees-io/kaniko[Kaniko], and then reports the data to the platform.

[source,yaml]
----
name: Deployment workflow
on:
  workflow_dispatch:
jobs:
  test:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://golang:1.20
        name: Build Go app
        kind: build
        run: |
          go build -v ./...
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Set up Docker Hub registry
        kind: deploy
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - id: kaniko-build
        uses: cloudbees-io/kaniko@v1
        name: Push image to OCI registry
        with:
          destination: index.docker.io/myorg/my-sample-go-app:${{cloudbees.version}}
      - id: register-deployed-artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        name: Register deployed artifact
        with:
          artifact_id: ${{ fromJSON(steps.kaniko-build.outputs.artifact-ids)['index.docker.io/myorg/my-sample-go-app:cloudbees.version'] }}
          target-environment: my-env
----

=== Full workflow example with register build action

The following workflow registers the build artifact to the platform with the link:https://github.com/cloudbees-io/register-build-artifact[register a build artifact action].
Then it deploys the artifact to the Docker `test` target environment and link:https://github.com/cloudbees-io/publish-evidence-item[publishes evidence] to the platform.

.Example platform workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  test:
    steps:
      - id: build
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: art1
          version: ${{ cloudbees.version }}
          url: docker.io/my-app/art1::${{ cloudbees.version }}
      - id: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact_id: ${{ steps.build.outputs.artifact-id }}
          target-environment: test
      - name: publish evidence
        with:
          content: This is evidence
        uses: cloudbees-io/publish-evidence-item@v1
----
--

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
