
= CloudBees action: Register an artifact deployed to an environment

Use this action to report artifact-related data to an environment from a CloudBees platform workflow run, for artifact traceability purposes.

[IMPORTANT]
====
This action version (v2.0) is the most recent release of the action.
Previous link:https://github.com/cloudbees-io/register-deployed-artifact/releases[releases] are deprecated.
Version 2.0 link:https://github.com/cloudbees-io/register-deployed-artifact/pull/10#pullrequestreview-3009677046[replaces multiple required inputs] with a single parameter, `artifact-id`.
====

== Prerequisites

Before using this action, you must first register the artifact you plan to deploy to an environment.
This registration saves the artifact information to the platform.

Do one of the following to save your artifact information to the platform:

* Use the link:https://github.com/cloudbees-io/register-build-artifact[Register a build artifact] action in your workflow in a step prior to using this action.

* Add a publishing step to your workflow prior to using this action.
For example, use one of the following actions:
** link:https://github.com/cloudbees-io/ecr-promote-image[]
** link:https://github.com/cloudbees-io/s3-upload-object[]
** link:https://github.com/cloudbees-io/crane[]
** link:https://github.com/cloudbees-io/helm-push[]
** link:https://github.com/cloudbees-io/jfrog-artifactory-promote-image[]
** link:https://github.com/cloudbees-io/jfrog-artifactory-upload-file[]
** link:https://github.com/cloudbees-io/kaniko[]

* Manually link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/artifacts#create-artifact-version[create an artifact version] in the UI.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `artifact-id`
| String
| Yes
| The unique identifier of an artifact.

| `target-environment`
| String
| Required if no job-level `environment` is specified.
| The environment where the deployment is located.  
The `target-environment` value overrides the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/dsl-syntax/jobs-job-id-environment[`jobs.<job_id>.environment`] value.

| `labels`
| String
| No
| A comma-separated list of artifact labels.

|===

== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
 jobs:
    register_artifact_version_to_my_env:
      environment: my_env
      steps:
        - name: Register deployed artifact
          uses: cloudbees-io/register-deployed-artifact@v2
          with:
            artifact-id: 1234abcd-56ef-ab78-9012-cdef78903456

----

=== Using optional inputs

The following example specifies artifact labels:

[source, yaml,role="default-expanded"]
----
 jobs:
    register_artifact_version_to_qa_env:
      environment: qa_env
      steps:
        - name: Register deployed artifact with labels
          uses: cloudbees-io/register-deployed-artifact@v2
          with:
            artifact-id: 1234abcd-56ef-ab78-9012-cdef78903456
            labels: label1,label2

----

=== Full workflow example with Kaniko

This example publishes an image with xref:build-tools:kaniko.adoc[Kaniko], and then reports the data to the platform.

[source, yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deployment workflow

on:
  workflow_dispatch:

jobs:
  build:
    outputs:
      artifact-id: ${{ fromJSON(steps.push-image.outputs.artifact-ids)[ format('index.docker.io/{0}/my-sample-go-app:{1}', vars.DOCKER_USERNAME, cloudbees.version) ] }}
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Go app
        uses: docker://golang:1.20
        kind: build
        run: |
          go build -v ./...
      - name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        kind: deploy
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to OCI registry
        id: push-image
        uses: cloudbees-io/kaniko@v1
        with:
          destination: index.docker.io/${{ vars.DOCKER_USERNAME }}/my-sample-go-app:${{cloudbees.version}}
  deploy:
    needs: build
    steps:
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ needs.build.outputs.artifact-id }}
          target-environment: dev
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
