apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    #environment: Test_env
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "testDeploymentRegister"
          version: "13.0.0"
          url: "docker.io/myapp/mytestimg:13.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3677"
