apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  success_valid_env_reg_artifact:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "f089759c-9a6c-4c5b-befb-d70ca006625c"
          target-environment: "Test_env"
          labels: "Enter,     your labels,here!    , Thanks."
