apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  missing_env_deploy:
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "testDeploymentRegister"
          version: "2.0.0"
          url: "docker.io/myapp/mytestimg:2.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3622"
  valid_env_deploy:
    environment: Test_env
    steps:
      - name: valid_env_deploy_success
        uses: cloudbees-io/register-deployed-artifact@v1
        continue-on-error: true
        with:
          name: "testDeploymentRegister3"
          version: "3.0.0"
          url: "docker.io/myapp/mytestimg:3.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3633"
  invalid_env_deploy:
    environment: invalid_env
    steps:
      - name: invalid_env_deploy_fail
        uses: cloudbees-io/register-deployed-artifact@v1
        continue-on-error: true
        with:
          name: "testDeploymentRegister3"
          version: "3.0.0"
          url: "docker.io/myapp/mytestimg:3.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3633"