apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  success_valid_env_reg_artifact:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        #continue-on-error: true
        with:
          name: "testDeploymentRegister3"
          version: "3.0.0"
          url: "docker.io/myapp/mytestimg:3.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3633"
          target-environment: "Test_env"

  # Error is thrown by dsl-engine in scenarios like "Invalid environment", 
  # "no name". "no version", causing the workflow to stop processing further and
  # control does not reach the action. Hence, not added.
  
#  error_missing_env_reg_artifact:
#   steps:
#      - name: Register deployed artifact with missing environment
#        id: error_missing_env
#        uses: cloudbees-io/register-deployed-artifact@v1
#        continue-on-error: true
#        with:
#          name: "testDeploymentRegister"
#          version: "2.0.0"
#          url: "docker.io/myapp/mytestimg:2.0.0"
#          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3622"
          

